name: Deploy TrackOn.ClienteServico API

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish API (Linux Self-Contained)
      run: |
        dotnet publish TrackOn.ClienteServico.API/TrackOn.ClienteServico.API.csproj \
        -c Release \
        -o publish/ \
        --self-contained true \
        -r linux-x64

    - name: Upload new build to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "publish/**"
        target: "/var/www/trackon-cliente"
        overwrite: true
        strip_components: 1

    - name: Restart API via Systemd
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Parando serviço..."
          sudo systemctl stop clienteservico.service || true

          echo "Reload no daemon..."
          sudo systemctl daemon-reload

          echo "Iniciando serviço..."
          sudo systemctl start clienteservico.service

          echo "Status do serviço:"
          sudo systemctl status clienteservico.service --no-pager
